# ╔══════════════════════════════════════════════════════════════════╗
# ║   AI Welcome  ──  personalised join messages, generated by AI    ║
# ╚══════════════════════════════════════════════════════════════════╝
"""Generates a warm welcome message for every new member.

To keep the key pool safe the bot generates a *batch* of welcomes in one API
call, stores them in a per-server pool and reuses them one by one. Only when
the pool is empty and the hourly budget allows it does it make another call.
When the budget is used up it falls back to static templates.
"""

from datetime import datetime

import asyncio

import discord
from discord.ext import commands

from utils.emoji import ZAI, TICK, CROSS, WARNING, ENABLE, DISABLE
from utils.ai_staff_core import db, now, ai_json

COLOR = 0xFF0000
AI_MODEL = "llama-3.1-8b-instant"

WELCOME_SYSTEM = (
    "You write short Discord welcome messages. Return JSON: "
    "{\"welcomes\":[\"...\",\"...\",\"...\"]}. Each welcome is one or two "
    "sentences (max 35 words), friendly and unique, and MUST contain the "
    "literal placeholder {user}. You may use {server}. Do not use markdown "
    "headers."
)

STYLES = {
    "friendly": "warm, kind and welcoming",
    "funny": "playful and lightly humorous",
    "professional": "polite and professional",
    "anime": "energetic, anime-style with emojis",
    "gaming": "gamer slang, hype and fun",
    "hype": "very excited and high energy",
}

FALLBACKS = {
    "friendly": "Welcome to {server}, {user}! We are happy to have you here.",
    "funny": "Look who showed up — {user} joined {server}! Grab a seat.",
    "professional": "Welcome, {user}. Thank you for joining {server}.",
    "anime": "Yosh! {user} has entered {server}! Have an amazing time~",
    "gaming": "GG {user}, you just joined {server}! Let the games begin.",
    "hype": "{user} is here!! Welcome to {server}, let's gooo!",
}


class AIWelcome(commands.Cog):
    """AI generated welcome messages with a pool + hourly budget."""

    def __init__(self, bot):
        self.bot = bot
        self.db = db()
        # serialise pool generation so a join wave cannot fire many AI calls
        self._gen_lock = asyncio.Lock()

    @staticmethod
    def help_custom():
        return (ZAI, "AI Welcome", "AI generated join messages.")

    def embed(self, title, description):
        return discord.Embed(title=title, description=description, color=COLOR)

    # ----------------------------- config -----------------------------
    def cfg(self, guild_id):
        row = self.db.execute(
            "SELECT enabled, channel, style, budget_per_hour FROM ai_welcome "
            "WHERE guild_id=?", (str(guild_id),)).fetchone()
        if not row:
            return {"enabled": 0, "channel": None, "style": "friendly",
                    "budget_per_hour": 5}
        return {"enabled": row[0], "channel": row[1], "style": row[2],
                "budget_per_hour": row[3] or 5}

    def set_cfg(self, guild_id, **fields):
        self.db.execute("INSERT OR IGNORE INTO ai_welcome (guild_id) VALUES (?)",
                        (str(guild_id),))
        for key, value in fields.items():
            self.db.execute(
                f"UPDATE ai_welcome SET {key}=? WHERE guild_id=?",
                (value, str(guild_id)))
        self.db.commit()

    # --------------------------- generation ---------------------------
    def _budget_left(self, guild_id, budget):
        hour = datetime.utcnow().strftime("%Y-%m-%d-%H")
        row = self.db.execute(
            "SELECT count FROM ai_welcome_log WHERE guild_id=? AND hour=?",
            (str(guild_id), hour)).fetchone()
        used = row[0] if row else 0
        return max(0, budget - used), hour, used

    def _bump_budget(self, guild_id, hour):
        self.db.execute(
            "INSERT OR IGNORE INTO ai_welcome_log (guild_id, hour, count) "
            "VALUES (?,?,0)", (str(guild_id), hour))
        self.db.execute(
            "UPDATE ai_welcome_log SET count=count+1 WHERE guild_id=? AND hour=?",
            (str(guild_id), hour))
        self.db.commit()

    async def _generate_pool(self, guild_id, guild_name, style):
        hint = STYLES.get(style, STYLES["friendly"])
        left, hour, _used = self._budget_left(guild_id, self.cfg(guild_id)["budget_per_hour"])
        if left <= 0:
            return []
        data = await ai_json(
            f"Server name: {guild_name}\nStyle: {hint}\nWrite 3 welcomes.",
            WELCOME_SYSTEM, retries=0, model=AI_MODEL, max_tokens=400)
        self._bump_budget(guild_id, hour)
        if isinstance(data, dict):
            welcomes = data.get("welcomes") or data.get("messages") or []
        elif isinstance(data, list):
            welcomes = data
        else:
            welcomes = []
        clean = [str(m).strip() for m in welcomes if str(m).strip()][:3]
        for message in clean:
            self.db.execute(
                "INSERT INTO ai_welcome_pool (guild_id, style, message, created_at) "
                "VALUES (?,?,?,?)", (str(guild_id), style, message[:600], now()))
        self.db.commit()
        return clean

    async def _next_greeting(self, guild_id, guild_name, style):
        row = self.db.execute(
            "SELECT id, message FROM ai_welcome_pool WHERE guild_id=? AND style=? "
            "ORDER BY id LIMIT 1", (str(guild_id), style)).fetchone()
        if row:
            self.db.execute("DELETE FROM ai_welcome_pool WHERE id=?", (row[0],))
            self.db.commit()
            return row[1]
        async with self._gen_lock:
            # re-check: another join may have filled the pool while we waited
            row = self.db.execute(
                "SELECT id, message FROM ai_welcome_pool WHERE guild_id=? AND style=? "
                "ORDER BY id LIMIT 1", (str(guild_id), style)).fetchone()
            if row:
                self.db.execute("DELETE FROM ai_welcome_pool WHERE id=?", (row[0],))
                self.db.commit()
                return row[1]
            await self._generate_pool(guild_id, guild_name, style)
            # _generate_pool stored the batch; consume the first entry so it is
            # not sent twice on the next join.
            row = self.db.execute(
                "SELECT id, message FROM ai_welcome_pool WHERE guild_id=? AND style=? "
                "ORDER BY id LIMIT 1", (str(guild_id), style)).fetchone()
            if row:
                self.db.execute("DELETE FROM ai_welcome_pool WHERE id=?", (row[0],))
                self.db.commit()
                return row[1]
        return FALLBACKS.get(style, FALLBACKS["friendly"])

    @staticmethod
    def _render(template, member, guild):
        return (str(template)
                .replace("{user}", member.mention)
                .replace("{server}", guild.name))

    # ----------------------------- commands ---------------------------
    @commands.group(name="aiwelcome", aliases=["aiwlc"],
                    invoke_without_command=True,
                    help="AI generated welcome messages for new members.")
    @commands.guild_only()
    async def aiwelcome(self, ctx):
        cfg = self.cfg(ctx.guild.id)
        state = f"{ENABLE} Enabled" if cfg["enabled"] else f"{DISABLE} Disabled"
        channel = f"<#{cfg['channel']}>" if cfg["channel"] else "Not set"
        p = ctx.clean_prefix
        await ctx.send(embed=self.embed(
            f"{ZAI} AI Welcome",
            f"**Status:** {state}\n**Channel:** {channel}\n"
            f"**Style:** `{cfg['style']}` • **Budget:** `{cfg['budget_per_hour']}/h`\n\n"
            f"`{p}aiwelcome enable #channel` • `disable`\n"
            f"`{p}aiwelcome channel #channel`\n"
            f"`{p}aiwelcome style <{'/'.join(STYLES)}>`\n"
            f"`{p}aiwelcome budget <1-20>` — AI generations per hour\n"
            f"`{p}aiwelcome preview [@member]` • `status` • `reset`"))

    @aiwelcome.command(name="enable", help="Enable AI welcomes in a channel.")
    @commands.has_permissions(manage_guild=True)
    async def enable(self, ctx, channel: discord.TextChannel = None):
        channel = channel or ctx.channel
        self.set_cfg(ctx.guild.id, enabled=1, channel=str(channel.id))
        await ctx.send(embed=self.embed(
            f"{TICK} AI Welcome Enabled", f"New members will be welcomed in {channel.mention}."))

    @aiwelcome.command(name="disable", help="Disable AI welcomes.")
    @commands.has_permissions(manage_guild=True)
    async def disable(self, ctx):
        self.set_cfg(ctx.guild.id, enabled=0)
        await ctx.send(embed=self.embed(f"{CROSS} AI Welcome Disabled",
                                        "Join messages stopped."))

    @aiwelcome.command(name="channel", help="Set the welcome channel.")
    @commands.has_permissions(manage_guild=True)
    async def channel(self, ctx, channel: discord.TextChannel):
        self.set_cfg(ctx.guild.id, channel=str(channel.id), enabled=1)
        await ctx.send(embed=self.embed(f"{TICK} Welcome Channel Set",
                                        f"Welcomes will go to {channel.mention}."))

    @aiwelcome.command(name="style", help="Choose the welcome tone.")
    @commands.has_permissions(manage_guild=True)
    async def style(self, ctx, style: str):
        style = style.lower()
        if style not in STYLES:
            return await ctx.send(embed=self.embed(
                f"{WARNING} Unknown Style",
                f"Choose one of: {', '.join('`%s`' % s for s in STYLES)}."))
        self.set_cfg(ctx.guild.id, style=style)
        self.db.execute("DELETE FROM ai_welcome_pool WHERE guild_id=?",
                        (str(ctx.guild.id),))
        self.db.commit()
        await ctx.send(embed=self.embed(f"{TICK} Style Updated",
                                        f"Welcomes will be `{style}`."))

    @aiwelcome.command(name="budget", help="Max AI generations per hour (1-20).")
    @commands.has_permissions(manage_guild=True)
    async def budget(self, ctx, amount: int):
        if not 1 <= amount <= 20:
            return await ctx.send(embed=self.embed(
                f"{WARNING} Invalid Budget", "Pick a number between 1 and 20."))
        self.set_cfg(ctx.guild.id, budget_per_hour=amount)
        await ctx.send(embed=self.embed(
            f"{TICK} Budget Updated",
            f"Up to `{amount}` AI generations per hour (`{amount * 3}` welcomes)."))

    @aiwelcome.command(name="preview", help="Preview a welcome message.")
    @commands.has_permissions(manage_guild=True)
    async def preview(self, ctx, member: discord.Member = None):
        member = member or ctx.author
        cfg = self.cfg(ctx.guild.id)
        async with ctx.typing():
            template = await self._next_greeting(ctx.guild.id, ctx.guild.name,
                                                 cfg["style"])
        await ctx.send(embed=self.embed(
            f"{ZAI} Welcome Preview", self._render(template, member, ctx.guild)))

    @aiwelcome.command(name="reset", help="Clear the cached welcome pool.")
    @commands.has_permissions(manage_guild=True)
    async def reset(self, ctx):
        self.db.execute("DELETE FROM ai_welcome_pool WHERE guild_id=?",
                        (str(ctx.guild.id),))
        self.db.commit()
        await ctx.send(embed=self.embed(f"{TICK} Pool Cleared",
                                        "New welcomes will be generated next time."))

    @aiwelcome.command(name="status", help="Show the welcome configuration.")
    @commands.guild_only()
    async def status(self, ctx):
        cfg = self.cfg(ctx.guild.id)
        pool = self.db.execute(
            "SELECT COUNT(*) FROM ai_welcome_pool WHERE guild_id=?",
            (str(ctx.guild.id),)).fetchone()[0]
        left, hour, used = self._budget_left(ctx.guild.id, cfg["budget_per_hour"])
        channel = f"<#{cfg['channel']}>" if cfg["channel"] else "Not set"
        await ctx.send(embed=self.embed(
            f"{ZAI} AI Welcome Status",
            f"Enabled: `{bool(cfg['enabled'])}`\n"
            f"Channel: {channel}\n"
            f"Style: `{cfg['style']}`\nPool: `{pool}` cached\n"
            f"Budget: `{used}/{cfg['budget_per_hour']}` used this hour (`{left}` left)"))

    # ----------------------------- listener ---------------------------
    @commands.Cog.listener()
    async def on_member_join(self, member: discord.Member):
        if member.bot or not member.guild:
            return
        cfg = self.cfg(member.guild.id)
        if not cfg["enabled"] or not cfg["channel"]:
            return
        channel = member.guild.get_channel(int(cfg["channel"]))
        if not channel:
            return
        template = await self._next_greeting(member.guild.id, member.guild.name,
                                             cfg["style"])
        try:
            await channel.send(self._render(template, member, member.guild))
        except discord.HTTPException:
            pass


async def setup(bot):
    await bot.add_cog(AIWelcome(bot))
